/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 graphs.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/graphs-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.graph_16.geometry} material={materials.gold} position={[-68.01, 5.07, -5.3]} />
      <mesh geometry={nodes.graph_15.geometry} material={materials.gold} position={[-58.7, 4.92, -5.25]} />
      <mesh geometry={nodes.graph_14.geometry} material={materials.gold} position={[-47.97, 4.81, -5.24]} />
      <mesh geometry={nodes.graph_13.geometry} material={materials.gold} position={[-38.17, 5.71, -5.46]} />
      <mesh geometry={nodes.graph_12.geometry} material={materials.gold} position={[-28.79, 5.06, -5.28]} />
      <mesh geometry={nodes.graph_11.geometry} material={materials.gold} position={[-17.81, 4.93, -4.78]} />
      <mesh geometry={nodes.graph_10.geometry} material={materials.gold} position={[-8.05, 5.18, -5.32]} />
      <mesh geometry={nodes.graph_9.geometry} material={materials.gold} position={[1.84, 5.81, -5.27]} />
      <mesh geometry={nodes.graph_8.geometry} material={materials.gold} position={[-68.95, 6.01, 5.17]} />
      <mesh geometry={nodes.graph_7.geometry} material={materials.gold} position={[-57.87, 5.48, 4.7]} />
      <mesh geometry={nodes.graph_6.geometry} material={materials.gold} position={[-48.62, 4.87, 5.11]} />
      <mesh geometry={nodes.graph_5.geometry} material={materials.gold} position={[-37.83, 5.22, 4.97]} />
      <mesh geometry={nodes.graph_4.geometry} material={materials.gold} position={[-28.37, 4.64, 4.9]} />
      <mesh geometry={nodes.graph_3.geometry} material={materials.gold} position={[-18.78, 5.72, 5.1]} />
      <mesh geometry={nodes.graph_2.geometry} material={materials.gold} position={[-7.88, 5.69, 5.09]} />
      <mesh geometry={nodes.graph_1.geometry} material={materials.gold} position={[1.34, 5.23, 5.08]} />
      <mesh geometry={nodes.graph_25.geometry} material={materials.gold} position={[1.47, -25.21, -5.47]} />
      <mesh geometry={nodes.graph_17.geometry} material={materials.gold} position={[0.22, -14.92, -24.52]} />
      <mesh geometry={nodes.graph_20.geometry} material={materials.gold} position={[0.45, -15.05, -54.7]} />
      <mesh geometry={nodes.graph_22.geometry} material={materials.gold} position={[1.27, -25.18, 25.33]} />
      <mesh geometry={nodes.graph_21.geometry} material={materials.gold} position={[1.12, -25.59, 35.46]} />
      <mesh geometry={nodes.graph_28.geometry} material={materials.gold} position={[1.1, -25.21, -34.67]} />
      <mesh geometry={nodes.graph_24.geometry} material={materials.gold} position={[1.41, -24.74, 4.79]} />
      <mesh geometry={nodes.graph_19.geometry} material={materials.gold} position={[0.33, -15.25, -44.95]} />
      <mesh geometry={nodes.graph_30.geometry} material={materials.gold} position={[1.38, -25.57, -54.48]} />
      <mesh geometry={nodes.graph_23.geometry} material={materials.gold} position={[0.99, -24.74, 15.48]} />
      <mesh geometry={nodes.graph_26.geometry} material={materials.gold} position={[1.12, -25.17, -15]} />
      <mesh geometry={nodes.graph_29.geometry} material={materials.gold} position={[1.44, -25.5, -44.94]} />
      <mesh geometry={nodes.graph_31.geometry} material={materials.gold} position={[1.15, -34.95, 35.16]} />
      <mesh geometry={nodes.graph_18.geometry} material={materials.gold} position={[0.32, -15.33, -34.83]} />
      <mesh geometry={nodes.graph_27.geometry} material={materials.gold} position={[1.26, -24.73, -24.64]} />
      <mesh geometry={nodes.graph_32.geometry} material={materials.gold} position={[1.26, -35.39, 24.98]} />
      <mesh geometry={nodes.graph_33.geometry} material={materials.gold} position={[0.52, -35.05, 14.95]} />
      <mesh geometry={nodes.graph_34.geometry} material={materials.gold} position={[0.51, -34.73, 4.83]} />
      <mesh geometry={nodes.graph_35.geometry} material={materials.gold} position={[0.52, -34.89, -5.16]} />
      <mesh geometry={nodes.graph_36.geometry} material={materials.gold} position={[1.22, -35.12, -15.61]} />
      <mesh geometry={nodes.graph_37.geometry} material={materials.gold} position={[1.3, -34.91, -25.62]} />
      <mesh geometry={nodes.graph_38.geometry} material={materials.gold} position={[1.18, -34.87, -34.49]} />
      <mesh geometry={nodes.graph_39.geometry} material={materials.gold} position={[1.18, -34.65, -44.79]} />
      <mesh geometry={nodes.graph_40.geometry} material={materials.gold} position={[0.63, -35.56, -54.88]} />
      <mesh geometry={nodes.graph_41.geometry} material={materials.gold} position={[1.24, -45.79, 35.05]} />
      <mesh geometry={nodes.graph_42.geometry} material={materials.gold} position={[1.14, -45.97, 24.77]} />
      <mesh geometry={nodes.graph_43.geometry} material={materials.gold} position={[1.57, -45.45, 14.11]} />
      <mesh geometry={nodes.graph_44.geometry} material={materials.gold} position={[1.31, -45.25, 4.72]} />
      <mesh geometry={nodes.graph_45.geometry} material={materials.gold} position={[0.22, -45.29, -5.29]} />
      <mesh geometry={nodes.graph_46.geometry} material={materials.gold} position={[0.99, -44.93, -15.03]} />
      <mesh geometry={nodes.graph_53.geometry} material={materials.gold} position={[-0.76, -54.93, 15.81]} />
      <mesh geometry={nodes.graph_52.geometry} material={materials.gold} position={[-0.9, -54.96, 24.98]} />
      <mesh geometry={nodes.graph_51.geometry} material={materials.gold} position={[-0.59, -55.05, 35.55]} />
      <mesh geometry={nodes.graph_49.geometry} material={materials.gold} position={[-0.7, -45.36, -45.41]} />
      <mesh geometry={nodes.graph_47.geometry} material={materials.gold} position={[-1.6, -44.87, -25.68]} />
      <mesh geometry={nodes.graph_48.geometry} material={materials.gold} position={[-0.71, -44.8, -34.2]} />
      <mesh geometry={nodes.graph_50.geometry} material={materials.gold} position={[-0.78, -45.4, -55.49]} />
      <mesh geometry={nodes.graph_54.geometry} material={materials.gold} position={[-0.69, -54.98, 5.34]} />
      <mesh geometry={nodes.graph_55.geometry} material={materials.gold} position={[-0.88, -54.7, -5.17]} />
      <mesh geometry={nodes.graph_56.geometry} material={materials.gold} position={[-0.78, -54.7, -14.19]} />
      <mesh geometry={nodes.graph_57.geometry} material={materials.gold} position={[-0.28, -54.16, -23.93]} />
      <mesh geometry={nodes.graph_58.geometry} material={materials.gold} position={[0.97, -54.46, -34.09]} />
      <mesh geometry={nodes.graph_80.geometry} material={materials.gold} position={[1.95, -75.03, -54.91]} />
      <mesh geometry={nodes.graph_84.geometry} material={materials.gold} position={[2.09, -84.6, 4.99]} />
      <mesh geometry={nodes.graph_85.geometry} material={materials.gold} position={[2.07, -84.77, -4.86]} />
      <mesh geometry={nodes.graph_64.geometry} material={materials.gold} position={[0.14, -65.4, 5.29]} />
      <mesh geometry={nodes.graph_83.geometry} material={materials.gold} position={[2.01, -84.73, 14.87]} />
      <mesh geometry={nodes.graph_82.geometry} material={materials.gold} position={[1.86, -84.64, 23.82]} />
      <mesh geometry={nodes.graph_63.geometry} material={materials.gold} position={[0.05, -65.13, 14.67]} />
      <mesh geometry={nodes.graph_61.geometry} material={materials.gold} position={[0.23, -65.47, 35.01]} />
      <mesh geometry={nodes.graph_65.geometry} material={materials.gold} position={[0.27, -66.05, -5.07]} />
      <mesh geometry={nodes.graph_62.geometry} material={materials.gold} position={[0.11, -65.35, 24.99]} />
      <mesh geometry={nodes.graph_78.geometry} material={materials.gold} position={[1.01, -75.43, -35.11]} />
      <mesh geometry={nodes.graph_77.geometry} material={materials.gold} position={[0.9, -74.91, -25.12]} />
      <mesh geometry={nodes.graph_76.geometry} material={materials.gold} position={[0.7, -74.52, -14.7]} />
      <mesh geometry={nodes.graph_75.geometry} material={materials.gold} position={[0.74, -74.49, -4.84]} />
      <mesh geometry={nodes.graph_74.geometry} material={materials.gold} position={[0.82, -74.86, 5.14]} />
      <mesh geometry={nodes.graph_73.geometry} material={materials.gold} position={[0.72, -75.1, 15.31]} />
      <mesh geometry={nodes.graph_69.geometry} material={materials.gold} position={[0.2, -65.03, -45.34]} />
      <mesh geometry={nodes.graph_72.geometry} material={materials.gold} position={[0.52, -75.22, 25.67]} />
      <mesh geometry={nodes.graph_71.geometry} material={materials.gold} position={[0.18, -75.01, 35.37]} />
      <mesh geometry={nodes.graph_70.geometry} material={materials.gold} position={[0.13, -64.63, -55.36]} />
      <mesh geometry={nodes.graph_68.geometry} material={materials.gold} position={[0.1, -64.85, -35.76]} />
      <mesh geometry={nodes.graph_59.geometry} material={materials.gold} position={[0.01, -55.46, -44.68]} />
      <mesh geometry={nodes.graph_67.geometry} material={materials.gold} position={[0.32, -65.14, -25.31]} />
      <mesh geometry={nodes.graph_66.geometry} material={materials.gold} position={[0.42, -65.24, -15.61]} />
      <mesh geometry={nodes.graph_79.geometry} material={materials.gold} position={[1.96, -75.11, -44.52]} />
      <mesh geometry={nodes.graph_60.geometry} material={materials.gold} position={[0.1, -55.25, -54.47]} />
      <mesh geometry={nodes.graph_81.geometry} material={materials.gold} position={[1.95, -84.64, 34.7]} />
    </group>
  )
}

useGLTF.preload('/graphs-transformed.glb')
