/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ring2.glb -T 
Files: ring2.glb [1.13MB] > ring2-transformed.glb [453.3KB] (60%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ring2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.diamonds.geometry} material={materials['Material_4.008']} position={[0, 2.053, 0]} scale={[1.123, 1, 1.075]} />
      <mesh geometry={nodes.black.geometry} material={materials.black_paint_mat} />
      <mesh geometry={nodes.body.geometry} material={materials.body} />
      <mesh geometry={nodes.core.geometry} material={materials.core} position={[0, 0.229, 0]} scale={[1.083, 1.096, 1.083]} />
    </group>
  )
}

useGLTF.preload('/ring2-transformed.glb')
