/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ring4.glb -T 
Files: ring4.glb [1.14MB] > ring4-transformed.glb [442.26KB] (61%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ring4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.body} />
      <mesh geometry={nodes.black.geometry} material={materials.Material_9} />
      <mesh geometry={nodes.diamond_stones.geometry} material={materials.diamond} />
      <mesh geometry={nodes.core.geometry} material={materials.core} />
    </group>
  )
}

useGLTF.preload('/ring4-transformed.glb')
